Added Rootly to Incident Management / Incident Response / IT Alerting ...
SquadcastHub/awesome-sre-tools pull request #11
Opened 2021-05-19 00:22 UTC by kwent

2021-05-20 07:27 UTC, raghuchinnannan requested changes
Please add your listing at the bottom of the section as mentioned in [Contributing](https://github.com/SquadcastHub/awesome-sre-tools/blob/master/CONTRIBUTING.md) doc.

2021-05-20 19:29 UTC, kwent commented
Done 👍🏻

2021-05-22 15:58 UTC, raghuchinnannan approved these changes

2021-05-22 15:59 UTC, merged

2021-05-22 15:59 UTC, raghuchinnannan commented
Merged, thanks.